### PR TITLE
feat: Add meaningful error for object schemas without properties.

### LINKED ISSUE #355: Improve error messages for unsupported-yet-compliant JsonSchemas
Excellent library, but it is a bit fiddly to get working for anything larger than a toy example because the parsing logic is very brittle and does not contain much validation. For example, a simple example taken from https://stackoverflow.com/a/25033301/323177 is valid JsonSchema but it throws the error `TypeError: Cannot convert undefined or null to object`:
```
{
    "description" : "schema validating people and vehicles",
    "type" : "object",
    "oneOf" : [
       {
        "type" : "object",
        "properties" : {
            "firstName" : {
                "type" : "string"
            },
            "lastName" : {
                "type" : "string"
            },
            "sport" : {
                "type" : "string"
            }
          }
      }, 
      {
        "type" : "object",
        "properties" : {
            "vehicle" : {
                "type" : "string"
            },
            "price" : {
                "type" : "integer"
            }
        },
        "additionalProperties":false
     }
]
}
```

This is caused because the top-level schema has field `"type": "object"` which causes the parser to call into `parseType` instead of `parseUnion`. It would be great if we could add some checks and logic to really identify what type is being received and throw a meaningful error in case of missing fields or other unexpected scenarios

Thanks!

### PR DESCRIPTION
**Pull request by yeldiRium**
This resolves #355.

### CODE REVIEW

**Comment by strangedev** [comment]
Looks good to me, but I wonder if the problem is deeper than just this check. Why does the type check not immediately catch that `properties` might be undefined?

**Comment by yeldiRium** [comment]
So far the type check was designed to only differentiate based on the content of the `type` property. We could introduce additional criteria to catch the problem earlier, but that wouldn't help us handle the problem better, since we unfortunately can't handle it either way, I think.

With the current implementation we first take a look at the type and then report errors that are specific to that type in the function that parses the type. This way the checks for type-specific criteria are located in the parsing function for the type.

**Comment by strangedev** [comment]
I don't understand what you mean when you say that we can't handle it.

What I'm trying to say is that we use `TranslatableObjectTypeJsonSchema` in `handleObjectType`, even though we haven't actually validated that the data we're reading is actually consistent with this type. We only check the presence of the `type` property, and then assume that the data is correctly formatted. I would expect that we used a type here that matches what we actually know about the data at this point (which would be that it has a `type` property, and an index signature for `string` that contains `unknown`). That way, we would have to put checks for every access to the data, and that would force us to build a more resilient parser.

**Comment by strangedev** [comment]
We can of course also skip these checks entirely and just let the parser crash when the data is malformed. But then we'd lose the ability to produce meaningful error messages.

**Comment by strangedev** [comment]
Isn't there some metaschema that we can use to parse the data?

**Comment by yeldiRium** [comment]
there is nothing premade we can use for this, since we decide on our own subset of JsonSchema that we want to support

**Comment by strangedev** [comment]
Then I guess we should do it. Of course we can still merge this PR first, but I think we should open a new issue for updating the types. While adding an error message for this specific case is an improvement, it's just a patch fix for a symptom of a larger issue with the codebase IMHO.

**Review by strangedev — APPROVED** [review]

**Pull request merged**
